### ISSUE TITLE
Your new version crashed

### ISSUE THREAD

**Issue by nghiant96** [bkdev98/react-native-incoming-call#24]
E/unknown:ReactNative: CatalystInstanceImpl caught native exception
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.finish()' on a null object reference
        at com.incomingcall.UnlockScreenActivity.dismissIncoming(UnlockScreenActivity.java:137)
        at com.incomingcall.IncomingCallModule.dismiss(IncomingCallModule.java:77)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:914)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:224)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:919)

**Comment by bkdev98** [comment]
Thanks I'll check again

**Comment by icc-guerrero** [comment]
Could you check [with this fork](https://github.com/UN-ICC/react-native-incoming-call)?  If it's fixed I will create a PR.
